### PR TITLE
Allows to build against system libs instead of bundled copy

### PR DESCRIPTION
**Pull request by twolife**

### CODE REVIEW

**Comment by twolife** [comment]
i didn't anticipated the github CI workflows and all the cross compiling issues :unamused:

**Comment by smallmodel** [comment]
It's best to do this change consistently for all other used libraries, like libvorbis, libogg, curl, opus, zlib. ioq3 Makefile has a parameter for each library to specify whether or not to use the bundled one.
It will be necessary to modify GitHub actions file to compile those libraries (as static) and use them in the project. Luckily they all use CMake except for libogg.

**Comment by twolife** [comment]
> It's best to do this change consistently for all other used libraries, like libvorbis, libogg, curl, opus, zlib. 

those libs are not used anywhere during the build of openmohaa, that's why I didn't add any option for them.

- curl use is guarded by `#ifdef USE_CURL` , that is not defined
- opus use is guarded by `#ifdef USE_CODEC_OPUS` , that is not defined
- vorbis use is guarded by `#ifdef USE_CODEC_VORBIS` , that is not defined
- zlib.h is referenced in code/qcommon/ioapi.c , but that file is not used.

I can 'rm -rf' those libs directories and openmohaa still builds fine.

> It will be necessary to modify GitHub actions

or I could preserve the status-quo and the default would be to still build them statically, and using the system libs would be opt-in ?

**Comment by smallmodel** [comment]
I didn't had too much interest on cleaning up unused libraries that I'm just learning about.
These can be omitted currently although some of them might be used in the future to introduce some features such as auto-download (using cURL), and VOIP (using opus).

For zlib I'm going to work on it, ioquake3 has a more modern implementation of unzip.c, zlib will be used.

System libs is opt-in as in ioquake3 (internal libs are used by default)

**Comment by smallmodel** [comment]
Looks good,
one correction, could you make it so it follows the same options name as ioq3 makefile: https://github.com/ioquake/ioq3/blob/4ee389b6b27feed82b19145ef49948839ed8dc9b/Makefile#L214 ?
Also, it's best to stick with common naming convention: capital letters and underscore for each word

Something like this:
```
if(NOT USE_INTERNAL_LIBS)
	set(USE_INTERNAL_LIBS ON)
endif()

option(USE_INTERNAL_JPEG "If set, use bundled libjpeg." ${USE_INTERNAL_LIBS})
option(USE_INTERNAL_MAD  "If set, use bundled libmad."  ${USE_INTERNAL_LIBS})
option(USE_INTERNAL_ZLIB "If set, use bundled zlib."    ${USE_INTERNAL_LIBS})
```

Otherwise, seems fine

**Pull request merged**
