### PR TITLE
Small correction in Level::EventSetClockSide: since STRING_KILLS > ST…

### PR DESCRIPTION
**Pull request by jvmap**
…RING_DRAW, the check should be on STRING_KILLS, not STRING_DRAW.

### CODE REVIEW

**Comment by mohabhassan** [comment]
Welcome back !
I'd commit to the dev branch .

**Comment by jvmap** [comment]
Thanks :). I'll make a new attempt soon, not overly experienced with git(hub) yet

**Comment by mohabhassan** [comment]
Neither am I , I keep spamming @Ley0k for help like an idiot lol.

**Comment by mohabhassan** [comment]
Oh ye btw incase you didn't know, this where the devs and modders gather for mohaa nowadays: http://www.x-null.net/forums/forum.php

**Comment by jvmap** [comment]
You're welcome, thanks for merging :+1:

**Comment by jvmap** [comment]
Thanks for letting me know. I won't be very active right now, as I'm off
for a vacation for a few weeks. Maybe afterwards. I was trying out if
openmohaa would be able to run my "sky is the limit" mod, just for the fun
of it. Well, not yet, as it turns out. But I'm really impressed with what
openmohaa can do. Amazing work, keep it up!

Cheers,
Jeroen

**Pull request merged**
