### PR TITLE
Implement UICheckBox

### PR DESCRIPTION
**Pull request by pryon**
Adds functioning checkboxes to the settings and multiplayer menus.

### CODE REVIEW

**Comment by smallmodel** [comment]
The destructor can be removed, the compiler will automatically call destructors of instanced classes like `str`
And the manual initialization of `str` members can be removed, as the compiler will automatically call `str`'s constructor

**Comment by smallmodel** [comment]
Ok, good job!

**Comment by gbudny** [comment]
Thank you.

I have to check it out.

@pryon

Do you plan to add lists from which you can select options, soldiers, etc.?

**Comment by pryon** [comment]
Hi @gbudny, yes, I'd like to do lists, bind tables, sliders, etc. as well so that the main menu functions correctly. But it depends on how much free time I'll have.

**Comment by smallmodel** [comment]
pull down menu, bind list, player selection menu, map list, is the priority for the UI client part

**Pull request merged**
